volumes:
  shared-data:
services:
  server:
    build:
      context: .
    ports:
      - '8080:8080'
    container_name: backend-server
    environment:
      - GOENV=dev
      - PORT=8080
      - DB_USER_NAME=test
      - DB_PASSWORD=testpw
      - DB_NAME=testdb
      - DB_HOST=db
      - DB_PORT=5432
      - ACCESS_SECRET=sadasdDWD@WQDWQ
      - REFRESH_SECRET=asd23e2dwsd23
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14-alpine
    container_name:  backend-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testpw
      - POSTGRES_DB=testdb
    healthcheck:
      test: bash -c "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      timeout: 10s
      retries: 10
